/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tX6LDEYod8X
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from "@/components/ui/select"

export function OnboardLanding() {
  return (
    <div className="flex min-h-dvh flex-col items-center justify-center bg-[url('/placeholder.svg')] bg-cover bg-center px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto w-full max-w-md space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-foreground">
            Welcome to CreatorHub
          </h2>
          <p className="mt-2 text-center text-sm text-muted-foreground">Let's get you set up with your profile.</p>
        </div>
        <form className="space-y-6" action="#" method="POST">
          <div>
            <Label htmlFor="profile-picture" className="sr-only">
              Profile Picture
            </Label>
            <div className="flex justify-center">
              <Avatar className="h-24 w-24 rounded-full">
                <AvatarImage src="/placeholder-user.jpg" alt="Profile Picture" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
            </div>
            <div className="mt-2 flex justify-center">
              <Button variant="outline">
                <UploadIcon className="mr-2 h-4 w-4" />
                Upload Photo
              </Button>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="first-name" className="block text-sm font-medium text-foreground">
                First Name
              </Label>
              <div className="mt-1">
                <Input
                  id="first-name"
                  name="first-name"
                  type="text"
                  autoComplete="given-name"
                  required
                  placeholder="Enter your first name"
                />
              </div>
            </div>
            <div>
              <Label htmlFor="last-name" className="block text-sm font-medium text-foreground">
                Last Name
              </Label>
              <div className="mt-1">
                <Input
                  id="last-name"
                  name="last-name"
                  type="text"
                  autoComplete="family-name"
                  required
                  placeholder="Enter your last name"
                />
              </div>
            </div>
          </div>
          <div>
            <Label htmlFor="date-of-birth" className="block text-sm font-medium text-foreground">
              Date of Birth
            </Label>
            <div className="mt-1">
              <Input id="date-of-birth" name="date-of-birth" type="date" required />
            </div>
          </div>
          <div>
            <Label htmlFor="content-type" className="block text-sm font-medium text-foreground">
              Content Type
            </Label>
            <div className="mt-1">
              <Select>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select content type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="lifestyle">Lifestyle</SelectItem>
                    <SelectItem value="fashion">Fashion</SelectItem>
                    <SelectItem value="travel">Travel</SelectItem>
                    <SelectItem value="food">Food</SelectItem>
                    <SelectItem value="tech">Tech</SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div>
            <Label htmlFor="social-links" className="block text-sm font-medium text-foreground">
              Social Links
            </Label>
            <div className="mt-1 grid grid-cols-3 gap-3">
              <Input id="twitter" name="twitter" type="text" placeholder="Twitter" />
              <Input id="instagram" name="instagram" type="text" placeholder="Instagram" />
              <Input id="linkedin" name="linkedin" type="text" placeholder="LinkedIn" />
            </div>
          </div>
          <div>
            <Button type="submit" className="w-full">
              Complete Onboarding
            </Button>
          </div>
        </form>
      </div>
    </div>
  )
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}
